color: sky
fieldLayouts:
  f16103c7-ba9f-4aa7-b97e-3380ad818ae9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-28T17:38:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: be191c37-111b-474f-a5c9-4bb241a90887
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-28T18:21:07+00:00'
            elementCondition: null
            fieldUid: 8a6a997d-4749-4e6b-ad86-4f16ac911030 # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37694d56-2cd1-4b18-bb20-4deb590e09d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec7e39bd-b9b0-415a-a445-ac1e4a9b42f9
        userCondition: null
handle: page
hasTitleField: true
icon: page
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
